name: Nalsoom Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Create application.yml
        run: |
          mkdir -p ./src/main/resources
          cat << EOF > ./src/main/resources/application.yml
          spring:
            datasource:
              url: ${{ secrets.DB_URL }}
              username: ${{ secrets.DB_USERNAME }}
              password: ${{ secrets.DB_PASSWORD }}
              driver-class-name: com.mysql.cj.jdbc.Driver
            
            jpa:
              database: mysql
                show-sql: false
                hibernate:
                  ddl-auto: none
                  naming:
                    physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
            
            server:
              port: 8080

            jasypt:
              encryptor:
                bean : jasyptEncryptor
                password : ${{ secrets.JASYPT_KEY }}
            
            custom:
              jwt:
                auth_header: Authorization
                token_type: Bearer 
                secret: ${{ secrets.JWT_KEY }}
                expiration_time: 86400000
                refresh_time: 8640000000

            seoul-data-key: ${{ secrets.SEOUL_DATA_KEY }}
            EOF

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload to GCP Compute Engine
        env:
          GCP_SSH_KEY: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          GCP_USER: ${{ secrets.GCP_USERNAME }}
          GCP_HOST: ${{ secrets.GCP_INSTANCE_IP }}
        run: |
          echo "$GCP_SSH_KEY" > gcp_key
          chmod 600 gcp_key
          scp -i gcp_key -o StrictHostKeyChecking=no build/libs/*.jar $GCP_USER@$GCP_HOST:/path/to/deploy/

      - name: End original application
        run : |
          CURRENT_PID=\$(pgrep -f nalsoom)
          if [ -n \"\$CURRENT_PID\" ]; then
            echo "현재 구동중인 애플리케이션 종료 (PID: \$CURRENT_PID)"
            kill \$CURRENT_PID
            sleep 5
          fi

      - name: Start application on GCP
        env:
          GCP_SSH_KEY: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          GCP_USER: ${{ secrets.GCP_USERNAME }}
          GCP_HOST: ${{ secrets.GCP_INSTANCE_IP }}
        run: |
          echo "$GCP_SSH_KEY" > gcp_key
          chmod 600 gcp_key
          ssh -i gcp_key -o StrictHostKeyChecking=no $GCP_USER@$GCP_HOST "nohup java -jar /path/to/deploy/your-app.jar > app.log 2>&1 &"
          echo "배포 완료"
          EOF"
        
          ssh gcp-instance "cd $DEPLOY_DIR && chmod +x deploy.sh && ./deploy.sh"
